// <auto-generated />
using System;
using BankAPI.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250703051558_Bank")]
    partial class Bank
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BankAPI.Model.BankAccount", b =>
                {
                    b.Property<int>("BankAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankAccountId"), 1L, 1);

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("BankAccountId");

                    b.ToTable("BankAccounts");

                    b.HasData(
                        new
                        {
                            BankAccountId = 1,
                            AccountNumber = "1234567890",
                            Balance = 1000m,
                            BankName = "Bank A",
                            EmployeeId = 1
                        },
                        new
                        {
                            BankAccountId = 2,
                            AccountNumber = "2345678901",
                            Balance = 1500m,
                            BankName = "Bank B",
                            EmployeeId = 2
                        },
                        new
                        {
                            BankAccountId = 3,
                            AccountNumber = "3456789012",
                            Balance = 2000m,
                            BankName = "Bank C",
                            EmployeeId = 3
                        },
                        new
                        {
                            BankAccountId = 4,
                            AccountNumber = "4567890123",
                            Balance = 2500m,
                            BankName = "Bank D",
                            EmployeeId = 4
                        },
                        new
                        {
                            BankAccountId = 5,
                            AccountNumber = "5678901234",
                            Balance = 3000m,
                            BankName = "Bank E",
                            EmployeeId = 5
                        },
                        new
                        {
                            BankAccountId = 6,
                            AccountNumber = "6789012345",
                            Balance = 3500m,
                            BankName = "Bank F",
                            EmployeeId = 6
                        },
                        new
                        {
                            BankAccountId = 7,
                            AccountNumber = "7890123456",
                            Balance = 4000m,
                            BankName = "Bank G",
                            EmployeeId = 7
                        },
                        new
                        {
                            BankAccountId = 8,
                            AccountNumber = "8901234567",
                            Balance = 4500m,
                            BankName = "Bank H",
                            EmployeeId = 8
                        },
                        new
                        {
                            BankAccountId = 9,
                            AccountNumber = "9012345678",
                            Balance = 5000m,
                            BankName = "Bank I",
                            EmployeeId = 9
                        },
                        new
                        {
                            BankAccountId = 10,
                            AccountNumber = "0123456789",
                            Balance = 5500m,
                            BankName = "Bank J",
                            EmployeeId = 10
                        });
                });

            modelBuilder.Entity("BankAPI.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "password1",
                            Username = "john_doe"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Password = "password2",
                            Username = "jane_smith"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Email = "emily.johnson@example.com",
                            FirstName = "Emily",
                            LastName = "Johnson",
                            Password = "password3",
                            Username = "emily_johnson"
                        },
                        new
                        {
                            EmployeeId = 4,
                            Email = "michael.brown@example.com",
                            FirstName = "Michael",
                            LastName = "Brown",
                            Password = "password4",
                            Username = "michael_williams"
                        },
                        new
                        {
                            EmployeeId = 5,
                            Email = "sarah.davis@example.com",
                            FirstName = "Sarah",
                            LastName = "Davis",
                            Password = "password5",
                            Username = "sarah_brown"
                        },
                        new
                        {
                            EmployeeId = 6,
                            Email = "david.miller@example.com",
                            FirstName = "David",
                            LastName = "Miller",
                            Password = "password6",
                            Username = "david_jones"
                        },
                        new
                        {
                            EmployeeId = 7,
                            Email = "laura.wilson@example.com",
                            FirstName = "Laura",
                            LastName = "Wilson",
                            Password = "password7",
                            Username = "laura_garcia"
                        },
                        new
                        {
                            EmployeeId = 8,
                            Email = "james.moore@example.com",
                            FirstName = "James",
                            LastName = "Moore",
                            Password = "password8",
                            Username = "james_martinez"
                        },
                        new
                        {
                            EmployeeId = 9,
                            Email = "linda.taylor@example.com",
                            FirstName = "Linda",
                            LastName = "Taylor",
                            Password = "password9",
                            Username = "linda_hernandez"
                        },
                        new
                        {
                            EmployeeId = 10,
                            Email = "robert.anderson@example.com",
                            FirstName = "Robert",
                            LastName = "Anderson",
                            Password = "password10",
                            Username = "robert_lopez"
                        });
                });

            modelBuilder.Entity("BankAPI.Model.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BankAPI.Model.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletId"), 1L, 1);

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WalletId");

                    b.ToTable("Wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
